{
  "openapi": "3.0.0",
  "info": {
    "version": "1.0.0",
    "title": "groupomania-api",
    "description": "",
    "license": {
      "name": "ISC"
    }
  },
  "tags": [
    {
      "name": "auth",
      "description": "Everything about the authenthication"
    },
    {
      "name": "posts",
      "description": "Everything about the posts"
    }
  ],
  "servers": [
    {
      "url": "https://localhost:3000"
    },
    {
      "url": "http://localhost:3000"
    }
  ],
  "security": [
    {
      "bearerAuth": []
    }
  ],
  "paths": {},
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    },
    "parameters": {
      "postIdParam": {
        "description": "post ID",
        "name": "id",
        "in": "path",
        "required": true,
        "schema": {
          "type": "string",
          "description": "ID of the post"
        }
      }
    },
    "schemas": {
      "errorMessage": {
        "type": "string",
        "maxLength": 256,
        "description": "A text message describing an error",
        "example": "Error during the request processing"
      },
      "errorObject": {
        "type": "object",
        "description": "An error defined by a name and a message",
        "properties": {
          "name": {
            "type": "string",
            "description": "The name of the error",
            "example": "Error"
          },
          "message": {
            "type": "string",
            "maxLength": 256,
            "description": "A text message describing the error",
            "example": "Error during the request processing"
          }
        },
        "example": {
          "name": "Error",
          "message": "Error during the request processing"
        }
      },
      "error": {
        "type": "object",
        "description": "An error defined by a name and a message",
        "properties": {
          "error": {
            "$ref": "#/components/schemas/errorObject"
          }
        },
        "example": {
          "error": {
            "name": "Error",
            "message": "Error during the request processing"
          }
        }
      },
      "user-credentials": {
        "type": "object",
        "description": "data relative to credentials sent back to a user after login or refresh (object structure -> user-credentials schema)",
        "properties": {
          "user": {
            "type": "object",
            "description": "User data (from the database)",
            "properties": {
              "id": {
                "type": "string",
                "description": "ID of the user that created the post"
              },
              "email": {
                "type": "string",
                "description": "E-mail of the user that created the post"
              },
              "firstName": {
                "type": "string",
                "description": "First name of the user that created the post"
              },
              "surName": {
                "type": "string",
                "description": "Surname of the user that created the post"
              },
              "pseudo": {
                "type": "string",
                "description": "Pseudonym of the user that created the post"
              },
              "role": {
                "type": "string",
                "description": "Role (user or admin) of the user that created the post"
              }
            },
            "required": ["id", "email", "firstName", "surName", "role"]
          },
          "accessToken": {
            "type": "string",
            "description": "signed access token (containing the user ID)"
          },
          "refreshToken": {
            "type": "string",
            "description": "signed refresh token (containing the user ID and the refresh token ID stored in the database)"
          }
        },
        "example": {
          "userId":{
            "id": "e5268c386c9b17c39bd6a17d",
            "email": "my-email-adress@email.com",
            "firstName": "Peter",
            "surName": "Smith",
            "pseudo": "Pete",
            "role": "User"
          },
          "accessToken":"string",
          "refreshToken":"string"
        }
      },
      "post": {
        "type": "object",
        "description": "data relative to a post (object structure -> post schema)",
        "properties": {
          "id": {
            "type": "string",
            "description": "ID of the post"
          },
          "createdAt": {
            "type": "string",
            "format": "date",
            "description": "Date of creation of the post"
          },
          "updatedAt": {
            "type": "string",
            "format": "date",
            "description": "Date of update of the post"
          },
          "text": {
            "type": "string",
            "description": "Content (text) of the post"
          },
          "imageUrl": {
            "type": "string",
            "description": "Content (image URL) of the post"
          },
          "imageAlt": {
            "type": "string",
            "description": "Content (image URL) of the post"
          },
          "authorId": {
            "type": "string",
            "description": "ID of the user that created the post"
          },
          "author": {
            "type": "object",
            "description": "User that created the post",
            "properties": {
              "firstName": {
                "type": "string",
                "description": "First name of the user that created the post"
              },
              "surName": {
                "type": "string",
                "description": "Surname of the user that created the post"
              },
              "pseudo": {
                "type": "string",
                "description": "Pseudonym of the user that created the post"
              }
            },
            "required": ["firstName", "surName"]
          },
          "likes": {
            "type": "array",
            "description": "Array of users (user IDs) that likes the post",
            "items": {
              "type": "object",
              "description": "User that created the post",
              "properties": {
                "id": {
                  "type": "string",
                  "description": "ID of a user that likes the post"
                }
              }
            },
            "minItems": 0
          },
          "dislikes": {
            "type": "array",
            "description": "Array of users (user IDs) that dislikes the post",
            "items": {
              "type": "object",
              "description": "User that created the post",
              "properties": {
                "id": {
                  "type": "string",
                  "description": "ID of a user that dislikes the post"
                }
              }
            },
            "minItems": 0
          },
          "comments": {
            "type": "array",
            "description": "Array of comments of the post",
            "items": {
              "$ref": "#/components/schemas/comment"
            },
            "minItems": 0
          }
        },
        "example": {
          "id":"cl6dl8yq10022b4muffz9isxl",
          "createdAt":"2022-08-03T12:31:30.505Z",
          "updatedAt":"2022-08-03T12:31:30.505Z",
          "text":"This is a post text",
          "imageUrl":"http://localhost:3000/images/Post1_image_20220701_162713.jpg",
          "imageAlt":"This is the description of the image",
          "authorId":"e5268c386c9b17c39bd6a17d",
          "likes":[{"id": "c386c9b17c39be5268d6a17d"},{"id": "9b17c39be5268dc386c6a17d"}],
          "dislikes":[{"id": "be5268dc386c6a9b17c3917d"},{"id": "a9b17c3917dbe5268dc386c6"}],
          "comments":[
            {
              "id": "cl977p9mb000at2vkmudnbxcp",
              "createdAt": "2022-08-03T12:31:30.505Z",
              "text": "This is a comment",
              "authorId": "e5268c386c9b17c39bd6a17d",
              "postId": "cl6dl8yq10022b4muffz9isxl"
            }
          ]
        }
      },
      "post-form-with-image": {
        "type": "object",
        "description": "data to use to create the post with image (object structure -> post-form-with-image schema)",
        "properties": {
          "text": {
            "type": "string",
            "description": "Content (text) of the post"
          },
          "imageAlt": {
            "type": "string",
            "description": "Description (alternative text) of the image (required if an image is provided)"
          }
        },
        "example": {
          "text":"This is a post text",
          "imageAlt":"This is the description of the image"
        }
      },
      "comment": {
          "type": "object",
          "description": "data relative to a comment (object structure -> comment schema)",
          "properties": {
            "id": {
              "type": "string",
              "description": "ID of the comment"
            },
            "createdAt": {
              "type": "string",
              "description": "Creation date of the comment"
            },
           "text": {
              "type": "string",
              "description": "Text of the comment"
            },
            "authorId": {
              "type": "string",
              "description": "ID of the author of the comment"
            },
            "postId": {
              "type": "string",
              "description": "ID of the post of the comment"
            }
          },
        "example": {
          "id": "cl977p9mb000at2vkmudnbxcp",
          "createdAt": "2022-08-03T12:31:30.505Z",
          "text": "This is a comment",
          "authorId": "e5268c386c9b17c39bd6a17d",
          "postId": "cl6dl8yq10022b4muffz9isxl"
        }
      }
    }
  }
}